package me.marthia.avanegar.presentation.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val theme_light_primary = Color(0xFFffca0a)
val theme_light_onPrimary = Color(0xFF4B3B00)
val theme_light_primaryContainer = Color(0xFF927300)
val theme_light_onPrimaryContainer = Color(0xFFFFFCF0)
val theme_light_secondary = Color(0xFFFFC300)
val theme_light_onSecondary = Color(0xFF4A3800)
val theme_light_secondaryContainer = Color(0x99FBF6D4)
val theme_light_onSecondaryContainer = Color(0xFF211C00)
val theme_light_tertiary = Color(0xFF628177)
val theme_light_onTertiary = Color(0xFFF0F3F2)
val theme_light_tertiaryContainer = Color(0xFFC0CDC9)
val theme_light_onTertiaryContainer = Color(0xFF19201E)
val theme_light_error = Color(0xFFB81F1E)
val theme_light_errorContainer = Color(0xFFFFDAD6)
val theme_light_onError = Color(0xFFFFFFFF)
val theme_light_onErrorContainer = Color(0xFF410002)
val theme_light_background = Color(0xFF161627)
val theme_light_onBackground = Color(0xFFFBFBFC)
val theme_light_outline = Color(0x8C44E84D)
val theme_light_outlineVariant = Color(0xFFE0E6E4)
val theme_light_inverseOnSurface = Color(0xFFF1F1EB)
val theme_light_inverseSurface = Color(0xFF2E2F2E)
val theme_light_inversePrimary = Color(0xFF5ADDAA)
val theme_light_surfaceTint = Color(0xFF006C4D)
val theme_light_scrim = Color(0xFF000000)
val theme_light_surface = Color(0xFF161627)
val theme_light_onSurface = Color(0xFFFBFBFC)
val theme_light_surfaceVariant = Color(0xFF1F2249)
val theme_light_onSurfaceVariant = Color(0xFF383A39)
val theme_light_surface_lowest = Color(0xFFB8B8D6)
val theme_light_surface_low = Color(0xFF3D3D6A)
val theme_light_surface_container = Color(0xFF161627)
val theme_light_surface_high = Color(0xFFFFFFFF)
val theme_light_surface_highest = Color(0xFF0A0A11)
val theme_light_surface_dim = Color(0xFF6F7573)
